AllCops:
  Exclude:
    - 'config/initializers/settings.rb'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'

AccessModifierIndentation:
  EnforcedStyle: outdent

Documentation:
  Enabled: false

GuardClause:
  Enabled: false